export default {
	groups: [{
		title: 'General',
		items: [{
			english: 'Button',
			chinese: '按钮'
		}, {
			disabled: true,
			english: 'Icon',
			chinese: '图标'
		}]
	}, {
		title: 'Layout',
		items: [{
			disabled: true,
			english: 'Grid',
			chinese: '栅格'
		}, {
			disabled: true,
			english: 'Layout',
			chinese: '布局'
		}]
	}, {
		title: 'Navigation',
		items: [{
			disabled: true,
			english: 'Affix',
			chinese: '固钉'
		}, {
			disabled: true,
			english: 'BackTop',
			chinese: '回到顶部'
		}, {
			disabled: true,
			english: 'Breadcrumb',
			chinese: '面包屑'
		}, {
			english: 'Dropdown',
			chinese: '下拉菜单'
		}, {
			english: 'Menu',
			chinese: '导航菜单'
		}, {
			disabled: true,
			english: 'Pagination',
			chinese: '分页'
		}, {
			disabled: true,
			english: 'Steps',
			chinese: '步骤条'
		}, {
			english: 'Tabs',
			chinese: '标签页'
		}]
	}, {
		title: 'Data Entry',
		items: [{
			disabled: true,
			english: 'AutoComplete',
			chinese: '自动完成'
		}, {
			english: 'Checkbox',
			chinese: '多选框'
		}, {
			disabled: true,
			english: 'Cascader',
			chinese: '级联选择'
		}, {
			disabled: true,
			english: 'DatePicker',
			chinese: '日期选择框'
		}, {
			disabled: true,
			english: 'Form',
			chinese: '表单'
		}, {
			english: 'Input',
			chinese: '输入框'
		}, {
			disabled: true,
			english: 'InputNumber',
			chinese: '数字输入框'
		}, {
			disabled: true,
			english: 'Mention',
			chinese: '提及'
		}, {
			english: 'Radio',
			chinese: '单选框'
		}, {
			disabled: true,
			english: 'Rate',
			chinese: '评分'
		}, {
			disabled: true,
			english: 'Select',
			chinese: '选择器'
		}, {
			disabled: true,
			english: 'Slider',
			chinese: '滑动输入条'
		}, {
			english: 'Switch',
			chinese: '开关'
		}, {
			disabled: true,
			english: 'TimePicker',
			chinese: '时间选择框'
		}, {
			disabled: true,
			english: 'Transfer',
			chinese: '穿梭框'
		}, {
			disabled: true,
			english: 'TreeSelect',
			chinese: '树选择'
		}, {
			disabled: true,
			english: 'Upload',
			chinese: '上传'
		}]
	}, {
		title: 'Data Display',
		items: [{
			disabled: true,
			english: 'Badge',
			chinese: '徽标数'
		}, {
			disabled: true,
			english: 'Card',
			chinese: '卡片'
		}, {
			disabled: true,
			english: 'Carousel',
			chinese: '走马灯'
		}, {
			disabled: true,
			english: 'Collapse',
			chinese: '折叠面板'
		}, {
			disabled: true,
			english: 'Calendar',
			chinese: '日历'
		}, {
			english: 'Popover',
			chinese: '气泡卡片'
		}, {
			disabled: true,
			english: 'Table',
			chinese: '表格'
		}, {
			disabled: true,
			english: 'Tag',
			chinese: '标签'
		}, {
			disabled: true,
			english: 'Timeline',
			chinese: '时间轴'
		}, {
			disabled: true,
			english: 'Tooltip',
			chinese: '文字提示'
		}, {
			disabled: true,
			english: 'Tree',
			chinese: '树形控件'
		}]
	}, {
		title: 'FeedBack',
		items: [{
			disabled: true,
			english: 'Alert',
			chinese: '警告提示'
		}, {
			disabled: true,
			english: 'Message',
			chinese: '全局提示'
		}, {
			english: 'Modal',
			chinese: '对话框'
		}, {
			english: 'Notification',
			chinese: '通知提醒框'
		}, {
			disabled: true,
			english: 'Popconfirm',
			chinese: '气泡确认框'
		}, {
			disabled: true,
			english: 'Progress',
			chinese: '进度条'
		}, {
			english: 'Spin',
			chinese: '加载中'
		}]
	}, {
		title: 'Other',
		items: [{
			disabled: true,
			english: 'Anchor',
			chinese: '锚点'
		}, {
			disabled: true,
			english: 'LocaleProvider',
			chinese: '国际化'
		}]
	}]
}
